#!/usr/bin/env python3

import click
from os import walk, path, rename

NTFS_PROBLEM_CHARS = set(
    [
        "<",
        ">",
        ":",
        '"',
        "/",
        '"',
        "|",
        "?",
        "*",
    ]
)


def contains_problem_character(filename):
    return any(
        ntfs_problem_char in filename for ntfs_problem_char in NTFS_PROBLEM_CHARS
    )


@click.command(help="Rename files that cause problems on ntfs")
@click.option("--dry-run", is_flag=True)
@click.argument(
    "filepath", type=click.Path(exists=True, file_okay=False, resolve_path=True)
)
def main(filepath, dry_run):
    for (dirpath, _, filenames) in walk(filepath):
        for filename in filenames:
            if contains_problem_character(filename):
                old_filename = filename
                new_filename = filename
                for problem_char in NTFS_PROBLEM_CHARS:
                    new_filename = new_filename.replace(problem_char, "_")

                old_filepath = path.join(dirpath, old_filename)
                new_filepath = path.join(dirpath, new_filename)
                if dry_run:
                    print(f"would rename {old_filepath} to {new_filepath}")
                else:
                    print(f"renaming {old_filepath} to {new_filepath}")
                    rename(old_filepath, new_filepath)


if __name__ == "__main__":
    main()
